# Generated by Django 4.1.2 on 2022-10-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isFeatured',
            field=models.BooleanField(default=False),
        ),
    ]
