# Generated by Django 4.1.2 on 2022-10-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_post_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
