# Generated by Django 4.1.2 on 2022-10-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click title to read blog post', max_length=255),
        ),
    ]
