# Generated by Django 4.1.2 on 2022-10-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_post_sub_category_alter_subcategory_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='product_images/')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.CharField(max_length=255)),
                ('product_url', models.TextField()),
                ('product_seller', models.CharField(max_length=255)),
                ('product_price', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='product',
            field=models.ManyToManyField(blank=True, to='theblog.product'),
        ),
    ]
