# Generated by Django 4.1.2 on 2022-10-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_product_post_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='chosen_product',
            field=models.BooleanField(default=False),
        ),
    ]
