# Generated by Django 4.1.2 on 2022-10-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0008_product_chosen_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_seller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_url',
        ),
        migrations.AddField(
            model_name='product',
            name='product_price_1',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price_2',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price_3',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='product_seller_1',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='product_seller_2',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='product_seller_3',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='product_url_1',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_url_2',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_url_3',
            field=models.TextField(default='default'),
        ),
    ]
