# Generated by Django 4.1.2 on 2022-10-19 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theblog', '0010_profile_youtube'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='snapchat',
            new_name='snapchat_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='tiktok',
            new_name='tiktok_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='youtube',
            new_name='youtube_url',
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
