# Generated by Django 4.1.2 on 2022-11-03 12:35

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0010_winningproduct_remove_product_chosen_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_keywords',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='min_read',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='photo_credit',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='winner_text',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='snippet_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='winningproduct',
            name='product_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
