# Generated by Django 4.1.2 on 2022-11-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0012_product_date_added_winningproduct_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='snippet_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price_1',
            field=models.CharField(blank=True, default='£', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price_2',
            field=models.CharField(blank=True, default='£', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price_3',
            field=models.CharField(blank=True, default='£', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_seller_1',
            field=models.CharField(blank=True, default='default', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_seller_2',
            field=models.CharField(blank=True, default='default', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_seller_3',
            field=models.CharField(blank=True, default='default', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url_1',
            field=models.TextField(blank=True, default='default', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url_2',
            field=models.TextField(blank=True, default='default', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url_3',
            field=models.TextField(blank=True, default='default', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='winningproduct',
            name='product_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='winningproduct',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='winningproduct',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='winningproduct',
            name='product_price_1',
            field=models.CharField(blank=True, default='£', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='winningproduct',
            name='product_price_2',
            field=models.CharField(blank=True, default='£', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='winningproduct',
            name='product_price_3',
            field=models.CharField(blank=True, default='£', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='winningproduct',
            name='product_seller_1',
            field=models.CharField(blank=True, default='default', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='winningproduct',
            name='product_seller_2',
            field=models.CharField(blank=True, default='default', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='winningproduct',
            name='product_seller_3',
            field=models.CharField(blank=True, default='default', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='winningproduct',
            name='product_url_1',
            field=models.TextField(blank=True, default='default', null=True),
        ),
        migrations.AlterField(
            model_name='winningproduct',
            name='product_url_2',
            field=models.TextField(blank=True, default='default', null=True),
        ),
        migrations.AlterField(
            model_name='winningproduct',
            name='product_url_3',
            field=models.TextField(blank=True, default='default', null=True),
        ),
    ]
